Keys update (#7)

diff --git a/tests/btechTests b/tests/btechTests
--- a/tests/btechTests
+++ b/tests/btechTests
@@ -24,7 +24,7 @@ cleanup() {
 
   for i in "${on_exit_items[@]}"
   do
-    echo "on_exit: $i"
+#    echo "on_exit: $i"
     eval $i
   done
 }
@@ -44,6 +44,7 @@ paramTest() {
   local beforeHex=${1?"Before hex"}
   local afterHex=${2?"After hex"}
   local paramName=${3?"Param Name"}
+  local tailIndex=${4-"1"}
 
   local afterImg=`mktemp`
   local beforeImg=`mktemp`
@@ -53,26 +54,46 @@ paramTest() {
   echo "Start $paramName"
   add_on_exit "{ rm -f $afterImg $beforeImg $tmpConf; }"
 
-  local baseAddress=`diff $beforeHex $afterHex |  egrep ">" | sed -r "s/> //g;s/:.*//g"`
-  xxd -r $beforeHex > $afterImg
-  xxd -r $afterHex > $beforeImg
+#  local baseAddress=`diff $beforeHex $afterHex |  egrep ">" | tail -n 1 | sed -r "s/> //g;s/:.*//g"`
+  local baseAddress=`diff $beforeHex $afterHex |  egrep ">" | tail -n $tailIndex | head -n1 | sed -r "s/> //g;s/:.*//g"`
+  echo "Base address: $baseAddress"
+  xxd -r $beforeHex > $beforeImg
+  xxd -r $afterHex > $afterImg
 
-  diff  <(xxd -s 0x$baseAddress -l $size -c 1 $beforeImg) <(xxd -s 0x$baseAddress -l $size -c 1 $afterImg) | egrep ">"
-  local byteAddress=`diff  <(xxd -s 0x$baseAddress -l 256 -c 1 $beforeImg) <(xxd -s 0x$baseAddress -l 256 -c 1 $afterImg) | egrep ">" | sed -r "s/> //g;s/:.*//g"`
+  diff  <(xxd -s 0x$baseAddress -l $size -c 1 $afterImg) <(xxd -s 0x$baseAddress -l $size -c 1 $beforeImg) | egrep ">" | tail -n $tailIndex | head -n1
+  local byteAddress=`diff  <(xxd -s 0x$baseAddress -l $size -c 1 $afterImg) <(xxd -s 0x$baseAddress -l $size -c 1 $beforeImg) | egrep ">" |tail -n $tailIndex | head -n 1 | sed -r "s/> //g;s/:.*//g"`
+  local byteAddressVal=`diff  <(xxd -s 0x$baseAddress -l $size -c 1 $afterImg) <(xxd -s 0x$baseAddress -l $size -c 1 $beforeImg) | egrep ">" | tail -n $tailIndex | head -n1 | awk '{print $3}'`
+  byteAddressVal=`printf %d 0x$byteAddressVal`
   echo "Target byte address: $byteAddress"
+  echo "Target byte Value: $byteAddressVal"
 
   ./dmrconfig $beforeImg > $tmpConf
-  sed -r -i "s/^$paramName:.*/$paramName: 00/g" $tmpConf
+#  vi $tmpConf
+  if ! egrep "^$paramName" $tmpConf ; then
+    echo "Could not find $param"
+    exit 1
+  fi
+
+  local confFileVal=`egrep "^$paramName" $tmpConf | awk '{printf $NF}'`
+
+  _testEq $confFileVal == $byteAddressVal "Conf file value matches value in hex"
+
+  sed -r -i "s/^$paramName:.*/$paramName: 0/g" $tmpConf
+  egrep "^$paramName" $tmpConf
   ./dmrconfig -c $beforeImg $tmpConf
 
   local after="`xxd -s 0x$byteAddress -l 1 -c 1 device.img | awk '{print $2}'`"
-  _testEq "00" == "$after" "$paramName"
+#  [ "00" != "$after" ] && vi $tmpConf
+#  [ "00" != "$after" ] && vim -d $beforeHex <(xxd device.img)
+  _testEq "00" == "$after" "$paramName" $byteAddress
 
-  sed -r -i "s/^$paramName:.*/$paramName: 01/g" $tmpConf
+  egrep "^$paramName" $tmpConf
+  sed -r -i "s/^$paramName:.*/$paramName: 1/g" $tmpConf
   egrep -i "^$paramName" $tmpConf
   ./dmrconfig -c $beforeImg $tmpConf
   after="`xxd -s 0x$byteAddress -l 1 -c 1 device.img | awk '{print $2}'`"
-  _testEq "01" == "$after" "$paramName"
+#  [ "01" != "$after" ] && vim -d $beforeHex <(xxd device.img)
+  _testEq "01" == "$after" "$paramName" $byteAddress
 }
 
 touchTest() {
@@ -94,8 +115,45 @@ main() {
   # TODO touchTest has been failing
 #  touchTest
 #  talkPermitTest
-  paramTest "./tests/bt6x2/talkPermit/analog.hex" "./tests/bt6x2/talkPermit/off.hex" "Talk Alert"
-  paramTest "./tests/bt6x2/keyBeep/on.hex" "./tests/bt6x2/keyBeep/off.hex" "Key Beep"
+
+  paramTest "./tests/bt6x2/digital_monitor/off.hex" "./tests/bt6x2/digital_monitor/double.hex" "Digital Monitor"
+
+  paramTest "./tests/bt6x2/currentChanA/scan1.hex" "./tests/bt6x2/currentChanA/tucson7.hex" "Channel A Zone Select"
+  paramTest "./tests/bt6x2/currentChanA/76.hex" "./tests/bt6x2/currentChanA/218.hex" "Channel A Zone Channel Select"
+
+  paramTest "./tests/bt6x2/currentChanB/scan1.hex" "./tests/bt6x2/currentChanB/favs76.hex" "Channel B Zone Select"
+  paramTest "./tests/bt6x2/currentChanB/76.hex" "./tests/bt6x2/currentChanB/138.hex" "Channel B Zone Channel Select"
+
+  paramTest "./tests/bt6x2/current_contact_display/off.hex" "./tests/bt6x2/current_contact_display/on.hex" "Current Contact Display"
+  paramTest "./tests/bt6x2/auto_backlight_duration/5s.hex" "./tests/bt6x2/auto_backlight_duration/10s.hex" "Auto Backlight Duration"
+
+  paramTest "./tests/bt6x2/idle_channel_tone/off.hex" "./tests/bt6x2/idle_channel_tone/on.hex" "Idle Channel Tone"
+  paramTest "./tests/bt6x2/talkPermit/analog.hex" "./tests/bt6x2/talkPermit/off.hex" "Talk Permit"
+  paramTest "./tests/bt6x2/keyBeep/on.hex"        "./tests/bt6x2/keyBeep/off.hex"    "Key Beep"
+
+  paramTest "./tests/bt6x2/pf1Short/volt.hex"    "./tests/bt6x2/pf1Short/scan.hex"    "Pf1 Short"
+  paramTest "./tests/bt6x2/pf2Short/monitor.hex" "./tests/bt6x2/pf2Short/digiMon.hex" "Pf2 Short"
+  paramTest "./tests/bt6x2/pf3Short/alarm.hex"   "./tests/bt6x2/pf3Short/txPower.hex" "Pf3 Short"
+
+  paramTest "./tests/bt6x2/p1Short/mainChoose.hex" "./tests/bt6x2/p1Short/monitor.hex" "P1 Short"
+  paramTest "./tests/bt6x2/p2Short/vfomr.hex"      "./tests/bt6x2/p2Short/monitor.hex" "P2 Short"
+
+  paramTest "./tests/bt6x2/pf1Long/off.hex" "./tests/bt6x2/pf1Long/volt.hex" "Pf1 Long"
+  paramTest "./tests/bt6x2/pf2Long/off.hex" "./tests/bt6x2/pf2Long/volt.hex" "Pf2 Long"
+  paramTest "./tests/bt6x2/pf3Long/off.hex" "./tests/bt6x2/pf3Long/volt.hex" "Pf3 Long"
+
+  paramTest "./tests/bt6x2/p1Long/off.hex" "./tests/bt6x2/p1Long/volt.hex" "P1 Long"
+  paramTest "./tests/bt6x2/p2Long/off.hex" "./tests/bt6x2/p2Long/volt.hex" "P2 Long"
+
+  # Oooff multi errors of diffs
+  # paramTest "./tests/bt6x2/gps/off.hex" "./tests/bt6x2/gps/on.hex" "Gps"
+   paramTest "./tests/bt6x2/gps_units/feet.hex" "./tests/bt6x2/gps_units/meters.hex" "GPS Units"
+   paramTest "./tests/bt6x2/get_gps_positioning/off.hex" "./tests/bt6x2/get_gps_positioning/on.hex" "Get GPS Positioning"
+   paramTest "./tests/bt6x2/timezone/GMT8.hex" "./tests/bt6x2/timezone/GMT-7.hex" "Timezone"
+
+   paramTest "./tests/bt6x2/analog_call_hold_time/10.hex" "./tests/bt6x2/analog_call_hold_time/2.hex" "Analog Call Hold Time"
+   paramTest "./tests/bt6x2/digit_call_hold_time/5.hex" "./tests/bt6x2/digit_call_hold_time/10.hex" "Digital Hold Time" 2
+   paramTest "./tests/bt6x2/digit_call_hold_time/5.hex" "./tests/bt6x2/digit_call_hold_time/10.hex" "Digital Manual Hold Time" 
 }
 
 main $@
